version: "3.9"

services:
  app:
    restart: on-failure:3
    build:
      context: .
    env_file:
      - .env
    networks:
      - crypto_performance

networks:
  crypto_performance:
    driver: bridge
